async (page) => {
  const errors=[], failedRequests=[], report=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error') errors.push(m.text());});
  page.on('response',r=>{if(r.status()>=400) failedRequests.push(`${r.status()} ${r.url()}`);});
  const assert=(condition,message)=>{if(!condition)throw new Error(message);};
  const base=page.url().split('#')[0];
  await page.evaluate(()=>localStorage.clear());
  await page.goto(base);
  const bank=await page.evaluate(async()=> (await import('./bank.js')).BANK);
  const overflow=async(label)=>{
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`${label}: horizontal overflow`);
  };
  await page.setViewportSize({width:1366,height:900});
  assert(await page.locator('button[data-start="2"]').isDisabled(),'Tier 2 must start locked');
  assert(await page.locator('button[data-start="3"]').isDisabled(),'Tier 3 must start locked');
  await page.screenshot({path:'output/playwright/home-chromebook.png',fullPage:true});
  await page.goto(base+'#tier-3');
  await page.waitForURL('**#home');
  report.push('No login; initial locks; direct-route lock verified');
  for(const width of [320,375,390,600,1366]) { await page.setViewportSize({width,height:900});await overflow(`Home ${width}`); }
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'output/playwright/home-phone.png',fullPage:true});
  await page.getByRole('button',{name:'Start quest'}).click();
  await overflow('Phone story');
  await page.getByRole('button',{name:'Make a decision'}).click();
  assert(await page.locator('.options button').count()===4,'Four options required');
  for(const button of await page.locator('.options button').all()) assert((await button.boundingBox()).height>=44,'Touch option too small');
  await page.locator('#hint').click();
  assert(await page.locator('.hint-note p').textContent()===bank[0].hint,'Exact supplied hint');
  await page.reload();
  assert((await page.locator('#hint').textContent()).includes('1 left'),'Hint count must persist');
  await page.locator('#hint').click();
  assert(await page.locator('#hint').isDisabled(),'Exactly two hint uses');
  await page.locator('[data-option="1"]').click();
  assert(await page.locator('.nudge p').textContent()===bank[0].hint,'Wrong answer hint must match');
  assert(await page.locator('.options button').count()===4,'Wrong answer permits retry');
  await overflow('Phone wrong answer and hints');
  for(const width of [320,375,390]) { await page.setViewportSize({width,height:844});await overflow(`Question ${width}`); }
  await page.screenshot({path:'output/playwright/question-phone.png',fullPage:true});
  await page.reload();
  assert(await page.locator('.nudge').count()===1,'Retry state persists');
  report.push('Two hints, wrong-story consequence, retry, reload and phone touch sizes verified');
  async function finishTier(tier,misses=[]) {
    for(let i=0;i<8;i++) {
      const q=bank[(tier-1)*8+i];
      if(await page.locator('#decision').count()) await page.locator('#decision').click();
      assert(await page.locator('.story').textContent()===q.story,`Story ${q.id}`);
      assert(await page.locator('.question').textContent()===q.question,`Question ${q.id}`);
      if(!(await page.locator('.hint-note').count())) await page.locator('#hint').click();
      assert(await page.locator('.hint-note p').textContent()===q.hint,`Hint ${q.id}`);
      const options=await page.locator('.options button').allTextContents();
      assert(JSON.stringify(options)===JSON.stringify(q.options.map((o,j)=>'ABCD'[j]+o)),`Options ${q.id}`);
      if(misses.includes(i) && !(await page.locator('.nudge').count())) await page.locator(`[data-option="${q.options.findIndex(o=>o!==q.answer)}"]`).click();
      await page.locator(`[data-option="${q.options.indexOf(q.answer)}"]`).click();
      assert(await page.locator('.success h2').textContent()===q.answer,`Answer ${q.id}`);
      await overflow(`Success ${q.id}`);
      await page.locator('#next').click();
    }
    assert(await page.locator('.badge-moment').count()===1,`Badge screen ${tier}`);
    await overflow(`Badge ${tier}`);
  }
  await finishTier(1,[0,1]);
  assert((await page.locator('.completion-stats').textContent()).includes('75%'),'First-answer score 75%');
  await page.getByRole('link',{name:'Back to map',exact:true}).click();
  await page.locator('.islands').waitFor();
  assert(await page.locator('button[data-start="2"]').isDisabled(),'75% remains locked');
  assert(await page.locator('.badge.earned').count()===1,'Tier 1 badge awarded');
  await page.locator('.islands button[data-start="1"]').click();
  await finishTier(1);
  assert((await page.locator('.xp strong').textContent()).includes('80 XP'),'Replay cannot farm XP');
  await page.locator('[data-start="2"]').click();
  await finishTier(2);
  await page.locator('[data-start="3"]').click();
  await finishTier(3);
  assert((await page.locator('.xp strong').textContent()).includes('240 XP'),'240 XP total');
  assert(await page.locator('.badge-moment h1').textContent()==='Master of Ratios','Final badge awarded');
  await page.screenshot({path:'output/playwright/final-badge-phone.png',fullPage:true});
  await page.reload();
  assert(await page.locator('.badge-moment h1').textContent()==='Master of Ratios','Final badge survives reload');
  await page.getByRole('link',{name:'Back to map',exact:true}).click();
  await page.locator('.islands').waitFor();
  assert(await page.locator('.badge.earned').count()===3,'All three badges on shelf');
  report.push('All 24 questions rendered exactly; 75% locked, replay unlocked; all badges; 240 XP; persistent progress verified');
  await page.getByRole('link',{name:'Teacher view'}).click();
  await page.locator('#roster-form').waitFor();
  await page.locator('#names').fill('Alina Test\nSam Test');
  await page.getByRole('button',{name:'Add to roster'}).click();
  assert(await page.locator('.roster-row').count()===3,'Roster created');
  assert((await page.locator('.roster-row').first().textContent()).includes('100% accuracy (8/8)'),'Teacher accuracy');
  for(const width of [320,375,390,1366]) { await page.setViewportSize({width,height:900});await overflow(`Teacher ${width}`); }
  await page.screenshot({path:'output/playwright/teacher-chromebook.png',fullPage:true});
  await page.getByRole('button',{name:'Play as Alina Test',exact:true}).click();
  await page.locator('.hero').waitFor();
  assert((await page.locator('.xp strong').textContent()).includes('0 XP'),'Students have separate progress');
  assert(await page.locator('button[data-start="2"]').isDisabled(),'New student tiers locked');
  await page.getByRole('button',{name:'Start quest'}).click();
  await page.locator('#decision').click();
  await page.locator('[data-option="0"]').click();
  await page.locator('#next').click();
  await page.getByRole('link',{name:'Teacher view'}).click();
  await page.locator('#roster-form').waitFor();
  assert((await page.locator('.roster-row').nth(1).textContent()).includes('1/8 complete'),'Roster shows student progress');
  assert((await page.locator('.roster-row').nth(2).textContent()).includes('No answers yet'),'Other student unchanged');
  await page.reload();
  assert(await page.locator('.roster-row').count()===3,'Roster survives reload');
  await page.getByRole('link',{name:'Back to quest map'}).click();
  await page.locator('.hero').waitFor();
  await page.getByRole('combobox',{name:'Choose student'}).selectOption('solo');
  assert((await page.locator('.xp strong').textContent()).includes('240 XP'),'Switch restores original student');
  report.push('Roster add, independent student records, per-tier progress and accuracy, switching, reload verified');
  assert(errors.length===0,`Console errors: ${errors.join('; ')}`);
  assert(failedRequests.length===0,`Failed assets: ${failedRequests.join('; ')}`);
  assert(await page.locator('img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0)),'Broken images');
  report.push('No console errors or failed assets; phone 320–390 px and Chromebook 1366 px layouts verified');
  return {pass:true,report,errors,failedRequests};
}
